dist: trusty
sudo: false
language: scala
# Activator & Travis image SBT conflicts
# https://github.com/travis-ci/travis-ci/issues/3140
before_install: unset SBT_OPTS JVM_OPTS
# according to http://docs.travis-ci.com/user/ci-environment/#CI-environment-OS
# every travis CI has a version of ruby installed
# that's why we can do this
before_script:
  - curl -L -o ./typesafe-activator-1.3.6-minimal.zip https://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-activator-1.3.6-minimal.zip
  - unzip -q typesafe-activator-1.3.6-minimal.zip

cache:
  directories:
    # caching scala stuff based on
    # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
  - openjdk7
scala:
  - 2.11.1
script:
  - activator-1.3.6-minimal/activator test
  # cleanup travis trick from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
notifications:
  irc: "chat.freenode.net#collins"
